# Generated by Django 5.1 on 2024-09-10 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
