# Generated by Django 5.1 on 2024-09-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_group_members_group_teacher_alter_group_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='time',
            field=models.TimeField(default='09:00'),
        ),
    ]
